// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFBIRmHUaWYDIZ7BDv7RjeYkaUatY8Yx0',
    appId: '1:787512723377:web:1a2066bb53db074e001f90',
    messagingSenderId: '787512723377',
    projectId: 'mychatapp-be1ff',
    authDomain: 'mychatapp-be1ff.firebaseapp.com',
    storageBucket: 'mychatapp-be1ff.firebasestorage.app',
    measurementId: 'G-SZQMNMHDNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACR7tEQJ-ryU5EBgSlpme8etk1v3WGhE8',
    appId: '1:787512723377:android:2a9cd15960ad3358001f90',
    messagingSenderId: '787512723377',
    projectId: 'mychatapp-be1ff',
    storageBucket: 'mychatapp-be1ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeRU8d8-R-BvNklP7t-J3xQapqcqPAh8Y',
    appId: '1:787512723377:ios:bac786830b1197ec001f90',
    messagingSenderId: '787512723377',
    projectId: 'mychatapp-be1ff',
    storageBucket: 'mychatapp-be1ff.firebasestorage.app',
    iosBundleId: 'com.nguyenngoc.ngocchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFBIRmHUaWYDIZ7BDv7RjeYkaUatY8Yx0',
    appId: '1:787512723377:web:c0b086a186075c72001f90',
    messagingSenderId: '787512723377',
    projectId: 'mychatapp-be1ff',
    authDomain: 'mychatapp-be1ff.firebaseapp.com',
    storageBucket: 'mychatapp-be1ff.firebasestorage.app',
    measurementId: 'G-DZ6B64GPEZ',
  );
}
